apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watsonx-ai-${appSuffix}
  namespace: ${argocdNS}
  labels:
    scope: namespace
    product: software-hub
spec:
  ignoreDifferences:
    - kind: "*"
      group: "*"
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: ${helmRepoURL}
    targetRevision: ${watsonx-ai-version}
    chart: ${watsonx-ai-chart}
    helm:
      valuesObject:
        global:
          licenseAccept: true
          operatorNamespace: ${operatorNS}
          instanceNamespace: ${instanceNS}
          blockStorageClass: ${blockStorageClass}
          fileStorageClass: ${fileStorageClass}
          imagePullPrefix: ${imagePullPrefix}
          imagePullSecret: ${imagePullSecret}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
