apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Howard-Luo/non-olm-cp4d-gitops-530.git
    targetRevision: main
    path: 8-olm
    kustomize: {}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
