apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zen-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  ignoreDifferences:
    - kind: "*"
      group: "*"
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://howard-luo.github.io/non-olm-cp4d-gitops-530/repos
    targetRevision: 6.3.0+20251122.162557.333
    chart: zen
    helm:
      valuesObject:
        global:
          licenseAccept: true
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          imagePullPrefix: icr.io
          imagePullSecret: ibm-entitlement-key
          installConfigImageDigest: sha256:f97f1b364a27acfe08b1c80d9ce91c25f07e6005a7ba821abf164c8e38925a04
          installConfigImageName: cpopen/cpd/olm-utils-v3
          releaseVersion: 5.2.0
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
