apiVersion: argoproj.io/v1alpha1
kind: Application
labels:
  component-id: watsonx-orchestrate
metadata:
  name: watsonx-orchestrate-cluster-gitops
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: watsonx-orchestrate-cluster-scoped
    helm:
      valuesObject:
        global:
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          installConfigImageDigest: sha256:9ac23ce4fcbd57be90855cfffb2e437ab9f88e4ef3fac33f049fcb08ca970885
          installConfigImageName: cp/cpd/olm-utils-premium-v4
          installConfigImagePullPrefix: cp.icr.io
          instanceNamespace: gitops-instance
          licenseAccept: true
          operatorNamespace: gitops-operator
          releaseVersion: 5.3.0
    path: ''
    repoURL: https://howard-luo.github.io/non-olm-cp4d-gitops-530/repos
    targetRevision: 7.0.0+20251209.173944.10066
